import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Game Meta</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div>
          <span className={styles.name}>Name:</span>
          <span>ISSAC MIN</span>
        </div>
        <div>
          TO DO
        </div>
      </main>
    </div>
  )
}
